apiVersion: v1
kind: Pod
metadata:
  name: simple-api-pod
  labels:
    app: api
spec:
  containers:
    - name: api-container
      image: k8s-ws-api
      imagePullPolicy: Never
      ports:
        - containerPort: 3000