apiVersion: v1
kind: Pod
metadata:
  name: sidecar-api-pod
spec:
  containers:
    - name: api-container
      image: k8s-ws-api
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
    - name: sidecar-logger
      image: curlimages/curl:latest
      command: ["/bin/sh"]
      args:
        - "-c"
        - |
          echo "Starting Health Check Sidecar..."
          while true; do
            echo "[Sidecar Log] Checking Main API Health..."
            curl -s http://localhost:3000/healthz
            echo ""
            sleep 1
          done